In [ ]:
import numpy as np

In [ ]:
# Define Matrices X and Y
X = np.array([[3, 2],
              [-2, 1]])

Y = np.array([[5],
              [7]])

In [ ]:
# Compute XY
XY = X @ Y
XY

array([[29],
       [-3]])

In [ ]:
# Define Matrices X and Y
X = np.array([[1, 1],
              [0, 1]])

Y = np.array([[0, -1],
              [1, 0]])

In [ ]:
# Compute XY
XY = X @ Y
XY

array([[ 1, -1],
       [ 1,  0]])

In [ ]:
# Define Matrices X and Y
X = np.array([[0, 2],
              [1, 0]])

Y = np.array([[1, -2],
              [1, 0]])

In [ ]:
# Compute XY
XY = X @ Y
XY

array([[ 2,  0],
       [ 1, -2]])

In [ ]:
# Define Matrices X and Y
X = np.array([[-3, 1],
              [2, 5]])

Y = np.array([[5, 3],
              [7, -3]])

In [ ]:
XY = X @ Y
XY

array([[ -8, -12],
       [ 45,  -9]])

In [ ]:
# Define Two 3x3 Matrices
X = np.array([[0, -2, 2],
              [5, 1, 5],
              [1, 4, -1]])

Y = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [ ]:
XY = X @ Y
XY

array([[ 6,  6,  6],
       [33, 44, 55],
       [ 6, 10, 14]])

In [ ]:
# Define Two 3x3 Matrices
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [ ]:
XY = X @ Y
XY

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
# Define Two 3x3 Matrices
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
XY = X @ Y
XY

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# Define Matrices A and B
A = np.array([[1, 4, -2],
              [3, 5, -6]])

B = np.array([[5, 2, 8, -1],
              [3, 6, 4, 5],
              [-2, 9, 7, -3]])

In [ ]:
# Compute AB
AB = A @ B
AB

array([[ 21,   8,  10,  25],
       [ 42, -18,   2,  40]])

In [ ]:
# Compute BA
# BA = B @ A
# BA

# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)
# Matrix multiplication BA is not defined due to incompatible dimensions.

In [ ]:
# Define Two 3x3 Matrices
R = np.array([[1, 0, 1],
              [1, 1, 0],
              [0, 0, 0]])

S = np.array([[0, 1, 0],
              [0, 0, 1],
              [1, 0, 1]])

In [ ]:
SoR = R @ S
SoR

array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 0]])

In [ ]:
RoS = S @ R
RoS

array([[1, 1, 0],
       [0, 0, 0],
       [1, 0, 1]])